apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apache
  namespace: default
spec:
  interval: 5m
  suspend: false
  chart:
    spec:
      chart: apache
      version: '>= 0.1.0 < 1.0.0'
      sourceRef:
        kind: HelmRepository
        name: github
        namespace: default
      interval: 1m    
