apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: github
  namespace: default
spec:
  type: oci
  interval: 5m0s
  url: oci://ghcr.io/anoopfirefox/myfluxrepo
  secretRef:
    name: github-credentials  
