apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZVzV2YjNCbWFYSmxabTk0T21kb2NGOHhZMGxLWjAxR2QzTklUWFJ4ZWpacE1qQlNjMVZZVURKSWNtcDFVWGd5ZVVWWU56RT0iCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewoJCQkiYXV0aCI6ICJZVzV2YjNCb1pXZGtaVEU1T1RVNlFYWmxibWRsY2lNa0pqSXlNQT09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson    
