apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: mysql
      version: '9.10.9'    
      sourceRef:
        kind: HelmRepository
        name: mysql
        namespace: flux-system
      interval: 1m
  values:
    auth:
      username: "myuser"
      password: "mypassword"
      database: "mydatabase"
