apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/nginx
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    indexHtml: |-
      <!doctype html>
      <html>
      <head>
        <title>Welcome to the page</</title>
      </head>
      <body>
        <h1>Changing a ConfigMap should restart the pod</h1>
        <h2>This is the second line in the Welcome page</h2>
      </body>
      </html>            
